// +build !ignore_autogenerated

/*
Copyright 2018 The play-operator Authors

Commercial software license.
*/
// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

// GetGeneratedDeepCopyFuncs returns the generated funcs, since we aren't registering them.
//
// Deprecated: deepcopy registration will go away when static deepcopy is fully implemented.
func GetGeneratedDeepCopyFuncs() []conversion.GeneratedDeepCopyFunc {
	return []conversion.GeneratedDeepCopyFunc{
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*PlayService).DeepCopyInto(out.(*PlayService))
			return nil
		}, InType: reflect.TypeOf(&PlayService{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*PlayServiceList).DeepCopyInto(out.(*PlayServiceList))
			return nil
		}, InType: reflect.TypeOf(&PlayServiceList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*PlayServiceSpec).DeepCopyInto(out.(*PlayServiceSpec))
			return nil
		}, InType: reflect.TypeOf(&PlayServiceSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*PlayServiceStatus).DeepCopyInto(out.(*PlayServiceStatus))
			return nil
		}, InType: reflect.TypeOf(&PlayServiceStatus{})},
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlayService) DeepCopyInto(out *PlayService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlayService.
func (in *PlayService) DeepCopy() *PlayService {
	if in == nil {
		return nil
	}
	out := new(PlayService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlayService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlayServiceList) DeepCopyInto(out *PlayServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlayService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlayServiceList.
func (in *PlayServiceList) DeepCopy() *PlayServiceList {
	if in == nil {
		return nil
	}
	out := new(PlayServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlayServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlayServiceSpec) DeepCopyInto(out *PlayServiceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlayServiceSpec.
func (in *PlayServiceSpec) DeepCopy() *PlayServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PlayServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlayServiceStatus) DeepCopyInto(out *PlayServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlayServiceStatus.
func (in *PlayServiceStatus) DeepCopy() *PlayServiceStatus {
	if in == nil {
		return nil
	}
	out := new(PlayServiceStatus)
	in.DeepCopyInto(out)
	return out
}
