linters:
  enable:
    - nakedret
    - interfacer
    - varcheck
    - deadcode
    - structcheck
    - misspell
    - maligned
    - ineffassign
    - goconst
    - goimports
    - errcheck
    - dupl
    - unparam
    - golint
    - staticcheck
    - unused
    - gosimple
    - gosec
issues:
  exclude-rules:
    - linters:
      - gosec
      text: "G110|G601|G404|G204|G306"
