entries:
  - description: >
      Changed the `go.operator-sdk.io` plugin to only write a `plugins` PROJECT field and
      run the OLM integration plugin if the project version is "3-alpha" or above.
    kind: change
    breaking: true
    migration:
      header: Upgrade your project from version "2" to "3-alpha"
      body: >
        The SDK's default Go plugin no longer supports OLM-related project files
        nor writes a `plugins` PROJECT field for projects scaffolded previously with
        `operator-sdk init --project-version=2`, Please migrate to project version "3-alpha"
        for support of these features by adding the following to your `PROJECT` file:

        ```yaml
        version: "3-alpha" # Updated from "2"
        layout: go.kubebuilder.io/v2
        plugins:
          go.sdk.operatorframework.io/v2-alpha: {}
        ```
