# entries is a list of entries to include in
# release notes and/or the migration guide
entries:
  - description: >
      The package name argument in the `operator-sdk cleanup` command is now optional. If the argument is not provided,
      SDK will use the `projectName` value from the `PROJECT` file as the package name.

    # kind is one of:
    # - addition
    # - change
    # - deprecation
    # - removal
    # - bugfix
    kind: "change"

    # Is this a breaking change?
    breaking: false
