entries:
  - description: >
      Added a scaffold marker `+kubebuilder:scaffold:manifestskustomizesamples` to `config/samples/kustomization.yaml`
      that allows updates without overwriting the entire file.
    kind: change
    breaking: true
    migration:
      header: Add the samples scaffold marker to your `config/samples/kustomization.yaml`
      body: >
        Add the `+kubebuilder:scaffold:manifestskustomizesamples` to your `config/samples/kustomization.yaml`
        file like so (using an example sample file):

        ```yaml
        resources:
        - cache_v1alpha1_memcached.yaml
        # +kubebuilder:scaffold:manifestskustomizesamples
        ```
