entries:
  - description: >
      Add '--kubeconfig' flag to '<run|cleanup> packagemanifests'.

    kind: addition

    breaking: false
  - description: >
      Deprecate '--kubeconfig' flag on the 'cleanup' subcommand. Use 'run packagemanifests'
      instead.

    kind: deprecation

    breaking: false
