# entries is a list of entries to include in
# release notes and/or the migration guide
entries:
  - description: >
      Remove `--operator-name` from `generate` subcommands in favor of using `project-name`
      from the PROJECT config file (v3-alpha+).
    kind: removal
    breaking: true
    migration:
      header: Remove `--operator-name` from scripts
      body: >
        The `--operator-name` flag has been removed from `generate bundle` and `generate packagemanifests`
        subcommands. Remove this flag from your scripts, and make sure the `project-name` key is set in
        your PROJECT file. If this key is not set, the current working directory's base name will be used.
