// Copyright 2020 The Operator-SDK Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package bundle

import (
	"errors"
	"os"
	"path/filepath"
	"strings"

	"github.com/operator-framework/operator-registry/pkg/lib/bundle"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
)

// newBundleBuildCmd returns a command that will build operator bundle image.
func newBundleBuildCmd() *cobra.Command {
	c := bundleCmd{}
	cmd := &cobra.Command{
		Use:   "build",
		Short: "Build an operator bundle image",
		Long: `The 'operator-sdk bundle build' command will build an operator
bundle image containing operator metadata and manifests, tagged with the
provided image tag. Metadata generated by this command defines this image
and should not be modified.

To write metadata and a bundle image Dockerfile to disk, set '--generate-only=true'.
Bundle metadata will be generated in <directory-arg>/metadata, and the Dockerfile
in <directory-arg>. This flag is useful if you want to build the operator's
bundle image manually.

More information on operator bundle images and metadata:
https://github.com/openshift/enhancements/blob/master/enhancements/olm/operator-bundle.md#docker

NOTE: bundle images are not runnable.`,
		Example: `The following invocation will build a test-operator bundle image using Docker.
This image will contain manifests for package channels 'stable' and 'beta':

$ operator-sdk bundle build \
    --directory ./deploy/olm-catalog/test-operator \
    --image-tag quay.io/example/operator:v0.1.0 \
    --package test-operator \
    --channels stable,beta \
    --default-channel stable \
    --overwrite

The following invocation will generate test-operator bundle metadata and
Dockerfile without building the image:

$ operator-sdk bundle build \
    --generate-only \
    --directory ./deploy/olm-catalog/test-operator \
    --package test-operator \
    --channels stable,beta \
    --default-channel stable`,
		RunE: func(cmd *cobra.Command, args []string) error {
			channels := strings.Join(c.channels, ",")
			if c.generateOnly {
				return bundle.GenerateFunc(c.directory, c.packageName, channels,
					c.channelDefault, true)
			}
			// An image tag is required for build only.
			if c.imageTag == "" {
				return errors.New("image tag must be set to build a bundle image")
			}
			// Clean up transient metadata and Dockerfile once the image is built,
			// as they are no longer needed.
			metaDir := filepath.Join(c.directory, "metadata")
			_, err := os.Stat(metaDir)
			metaExists := os.IsExist(err)
			dockerFile := filepath.Join(c.directory, "Dockerfile")
			_, err = os.Stat(dockerFile)
			dockerFileExists := os.IsExist(err)
			defer func() {
				if !metaExists {
					_ = os.RemoveAll(metaDir)
				}
				if !dockerFileExists {
					_ = os.RemoveAll(dockerFile)
				}
			}()
			return bundle.BuildFunc(c.directory, c.imageTag, c.imageBuilder,
				c.packageName, channels, c.channelDefault, c.overwrite)
		},
	}

	cmd.Flags().BoolVarP(&c.generateOnly, "generate-only", "g", false,
		"Generate metadata and a Dockerfile on disk without building the bundle image")
	cmd.Flags().StringVarP(&c.directory, "directory", "d", "",
		"The directory where bundle manifests are located")
	if err := cmd.MarkFlagRequired("directory"); err != nil {
		log.Fatalf("Failed to mark `directory` flag for `build` subcommand as required")
	}
	cmd.Flags().StringVarP(&c.packageName, "package", "p", "",
		"The name of the package that bundle image belongs to")
	if err := cmd.MarkFlagRequired("package"); err != nil {
		log.Fatalf("Failed to mark `package` flag for `build` subcommand as required")
	}
	cmd.Flags().StringSliceVarP(&c.channels, "channels", "c", nil,
		"The list of channels that bundle image belongs to")
	if err := cmd.MarkFlagRequired("channels"); err != nil {
		log.Fatalf("Failed to mark `channels` flag for `build` subcommand as required")
	}
	// '--image-tag' is only required for 'build'.
	cmd.Flags().StringVarP(&c.imageTag, "image-tag", "t", "",
		"The image tag applied to the bundle image, ex. example.com/test-operator:v0.1.0")
	cmd.Flags().StringVarP(&c.imageBuilder, "image-builder", "b", "docker",
		"Tool to build container images. One of: [docker, podman, buildah]")
	cmd.Flags().StringVarP(&c.channelDefault, "default-channel", "e", "",
		"The default channel for the bundle image")
	cmd.Flags().BoolVarP(&c.overwrite, "overwrite", "o", false,
		"To overwrite annotations.yaml locally if existed. By default, overwrite is set to `false`.")

	return cmd
}
