apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregation-memcached-subrole
  labels:
    rbac.example.memcached.com/aggregate-to-aggregation-memcached: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - update
