apiVersion: v1
kind: Pod
metadata:
  name: -test
spec:
  restartPolicy: Never
  containers:
  - name: -test
    image: 
    imagePullPolicy: Always
    command: ["/go-test.sh"]
    env:
      - name: 
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
