name: Check Markdown links

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.2
      with:
        max-depth: 1
        config-file: '.github/workflows/markdown-link-check-config.json'
